const nunjucks = require('nunjucks');
const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');

nunjucks.configure(path.join(rootDir, 'src'), {
    autoescape: false,
    trimBlocks: true,
    lstripBlocks: true,
});

const pages = [
    { template: 'pages/index.njk', output: 'index.html' },
];

pages.forEach(({ template, output }) => {
    const html = `<!-- Generated by scripts/build.js — edit src/${template} instead -->\n` + nunjucks.render(template);
    const outputPath = path.join(rootDir, output);
    fs.writeFileSync(outputPath, html);
    console.log(`Built ${output}`);
});
