name: Generate Sitemap
run-name: ${{ github.actor }} Generated the Sitemap 🚀
on:
  push:
    branches: [ main ]
jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://daqh.github.io/
        sitemap-format: txt
    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Automated sitemap update"
        body: > 
          Sitemap updated by the [generate-sitemap](https://github.com/cicirello/generate-sitemap)
          GitHub action. Automated pull-request generated by the
          [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
          "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
          "url-count = ${{ steps.sitemap.outputs.url-count }}"
          "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
